template: true   # required for local templates.
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

pipelines:
       
  - name: Use_The_CLI
    configuration:
      jfrogCliVersion: 2
    steps:

#Execute the plugin
      - name: Get_All_Ignored_violations
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
          integrations:
            - name: token_fabienl
            - name: token_pseme
        execution:
          onStart:
            - configure_jfrog_cli --artifactory-url ${int_token_fabienl_url}/artifactory --access-token ${int_token_fabienl_accessToken} --server-name fabienl
            - jf c s
            - jf xr curl -X POST -H "Content-Type:application/json" /api/v1/violations/ignored\?limit\=2000 -d '{}'| jq '.' > all_ignored_violations.json
          onExecute:
            - ls -all
            - cat all_ignored_violations.json
